package org.learn.spark;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.Set;

/**
 * A wrapper around for an input file containing a list of what we think are "boring" words
 * The list was generated by adding most commons words in the english language
 * This list of words is small sample of data and don't need to distribute this data
 */
public class Utils {

    private static Set<String> borings = new HashSet<String>();

    static {
        InputStream is = Main.class.getResourceAsStream("/boring-english.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(is));
        br.lines().forEach(it -> borings.add(it));
    }

    /**
     * returns true if we think the word is boring
     *
     * @param word
     * @return
     */
    public static boolean isBoring(String word){
        return borings.contains(word);
    }

    public static boolean isNotBoring(String word){
        return !isBoring(word);
    }
}
